create table director
(
    id         varchar(255) not null,
    name       varchar(255),
    picture    varchar(255),
    bio        varchar(255),
    movies     jsonb,
    version    integer,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    primary key (id)
);
create table director_history
(
    id           integer generated by default as identity,
    aggregate_id varchar(255),
    version      integer,
    operation    varchar(255),
    payload      jsonb,
    created_at   timestamp(6) with time zone,
    primary key (id)
);
