create table movie
(
    id           varchar(255) not null,
    name         varchar(255),
    genre        varchar(255),
    actors       jsonb,
    directors    jsonb,
    budget       numeric(38, 2),
    release_date date,
    version      integer,
    created_at   timestamp(6) with time zone,
    updated_at   timestamp(6) with time zone,
    primary key (id)
);
create table movie_history
(
    id           integer generated by default as identity,
    aggregate_id varchar(255),
    version      integer,
    operation    varchar(255),
    payload      jsonb,
    created_at   timestamp(6) with time zone,
    primary key (id)
);